/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nik.rsvpreader;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nikhil Gupta <nikhilgupta@programmer.net>
 */
public class Reader extends javax.swing.JFrame {
    private final core ReaderCore;
    private boolean isText;
    
    /**
     * Creates new form Reader
     */
    public Reader() {
        initComponents();isText=false;
        ReaderCore = new core(lblmain,slider);//initme("This is a Sample Text made from many words which are not required");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFileDialog = new javax.swing.JFileChooser();
        jMenu3 = new javax.swing.JMenu();
        btnsettings = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblmain = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        slider = new javax.swing.JSlider();
        lblcurrent = new javax.swing.JLabel();
        lblmax = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();
        btnplay = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuopen = new javax.swing.JMenuItem();
        mnutype = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnupaste = new javax.swing.JMenuItem();
        mnuhelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        openFileDialog.setAccessory(mnuopen);
        openFileDialog.setApproveButtonText("");
        openFileDialog.setDialogTitle("Select a text File");
        openFileDialog.setToolTipText("");
        openFileDialog.getAccessibleContext().setAccessibleName("");
        openFileDialog.setFileFilter(new FileNameExtensionFilter("Text Documents","txt"));

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open RSVP Reader");

        btnsettings.setMnemonic('s');
        btnsettings.setText("Settings");
        btnsettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsettingsActionPerformed(evt);
            }
        });

        lblmain.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblmain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmain.setText("Text Here");

        slider.setMaximum(1);
        slider.setValue(0);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        lblcurrent.setText("0");

        lblmax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmax.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblcurrent, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblmain, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnStop.setMnemonic('t');
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnplay.setText("Play");
        btnplay.setEnabled(false);
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });

        jMenu1.setMnemonic('f');
        jMenu1.setText("File");

        mnuopen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnuopen.setMnemonic('o');
        mnuopen.setText("Open");
        mnuopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuopenActionPerformed(evt);
            }
        });
        jMenu1.add(mnuopen);

        mnutype.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnutype.setMnemonic('t');
        mnutype.setText("Type");
        mnutype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnutypeActionPerformed(evt);
            }
        });
        jMenu1.add(mnutype);
        jMenu1.add(jSeparator1);

        mnuexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mnuexit.setMnemonic('x');
        mnuexit.setText("Exit");
        mnuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuexitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('e');
        jMenu2.setText("Edit");

        mnupaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mnupaste.setMnemonic('p');
        mnupaste.setText("Paste from Clipboard");
        mnupaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnupasteActionPerformed(evt);
            }
        });
        jMenu2.add(mnupaste);

        jMenuBar1.add(jMenu2);

        mnuhelp.setMnemonic('h');
        mnuhelp.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setMnemonic('C');
        jMenuItem1.setText("Help Contents");
        mnuhelp.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem2.setMnemonic('V');
        jMenuItem2.setText("Visit Website");
        mnuhelp.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setMnemonic('A');
        jMenuItem3.setText("About");
        mnuhelp.add(jMenuItem3);

        jMenuBar1.add(mnuhelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsettings))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsettings)
                    .addComponent(btnStop)
                    .addComponent(btnplay)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsettingsActionPerformed
        // TODO add your handling code here:
        Settings s =new Settings(ReaderCore);
        s.setVisible(true);
    }//GEN-LAST:event_btnsettingsActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        ReaderCore.stop();
        btnplay.setText("Play");
        btnplay.setSelected(false);
        lblmain.setText(ReaderCore.getWordat(0));
        slider.setValue(0);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
        if(null==btnplay.getText())throw new IllegalStateException("Only Two States are possible");
        else // TODO add your handling code here:
        switch (btnplay.getText()) {
            case "Pause":
                ReaderCore.pause();
                btnplay.setText("Play");
                break;
            case "Play":
                ReaderCore.start();
                btnplay.setText("Pause");
                break;
            default:
                throw new IllegalStateException("Only Two States are possible");
        }
    }//GEN-LAST:event_btnplayActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        // TODO add your handling code here:
        lblcurrent.setText(Integer.toString(slider.getValue()));
        lblmax.setText(Integer.toString(slider.getMaximum()));
        //if(slider.getValue()==0){btnplay.setText("Play");btnplay.setSelected(false);}
        if(ReaderCore.getState()==core.State.Paused)lblmain.setText(ReaderCore.getWordat(slider.getValue()));;
    }//GEN-LAST:event_sliderStateChanged

    private void mnuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuexitActionPerformed

    private void mnupasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnupasteActionPerformed
        // TODO add your handling code here:
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Clipboard clipboard = toolkit.getSystemClipboard();
        try{String result = (String) clipboard.getData(DataFlavor.stringFlavor);initme(result);}catch(UnsupportedFlavorException | IOException e){e.printStackTrace();}
    }//GEN-LAST:event_mnupasteActionPerformed

    private void mnuopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuopenActionPerformed
        // TODO add your handling code here:
        if(openFileDialog.showOpenDialog(jPanel1)==JFileChooser.APPROVE_OPTION){
            try{
                Scanner sc = new Scanner(openFileDialog.getSelectedFile());
                String str ="";
                while(sc.hasNext())str+=" "+sc.nextLine();
                initme(str);
            }catch(FileNotFoundException e){e.printStackTrace();}
        }
    }//GEN-LAST:event_mnuopenActionPerformed

    private void mnutypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnutypeActionPerformed
        // TODO add your handling code here:
        typer tp=new typer();
        tp.setVisible(true);
    }//GEN-LAST:event_mnutypeActionPerformed

    private void initme(String s){
        ReaderCore.stop();
        if(s==null || s.isEmpty()){isText=false;}
        else{
            isText=true;
            ReaderCore.setString(s);
            lblmain.setText(ReaderCore.getWordat(0));
            slider.setMaximum(s.split(" ").length);
        }
        btnplay.setEnabled(isText);
    }
   
//<editor-fold desc="Untouched Code">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Reader().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStop;
    private javax.swing.JToggleButton btnplay;
    private javax.swing.JButton btnsettings;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblcurrent;
    private javax.swing.JLabel lblmain;
    private javax.swing.JLabel lblmax;
    private javax.swing.JMenuItem mnuexit;
    private javax.swing.JMenu mnuhelp;
    private javax.swing.JMenuItem mnuopen;
    private javax.swing.JMenuItem mnupaste;
    private javax.swing.JMenuItem mnutype;
    private javax.swing.JFileChooser openFileDialog;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
}//</editor-fold>